# Generated by Django 4.2.4 on 2023-09-14 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness_level', models.IntegerField(default=3)),
                ('stress_level', models.IntegerField(default=3)),
                ('relaxation_level', models.IntegerField(default=3)),
                ('energy_level', models.IntegerField(default=3)),
                ('creativity_level', models.IntegerField(default=3)),
                ('focus_level', models.IntegerField(default=3)),
                ('social_level', models.IntegerField(default=3)),
                ('motivation_level', models.IntegerField(default=3)),
                ('confidence_level', models.IntegerField(default=3)),
                ('contentment_level', models.IntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('happiness_level', models.IntegerField(default=3)),
                ('stress_level', models.IntegerField(default=3)),
                ('relaxation_level', models.IntegerField(default=3)),
                ('energy_level', models.IntegerField(default=3)),
                ('creativity_level', models.IntegerField(default=3)),
                ('focus_level', models.IntegerField(default=3)),
                ('social_level', models.IntegerField(default=3)),
                ('motivation_level', models.IntegerField(default=3)),
                ('confidence_level', models.IntegerField(default=3)),
                ('contentment_level', models.IntegerField(default=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
