# Generated by Django 4.2.4 on 2023-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moodtracker", "0002_mooddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="mooddata",
            name="mood_emoji",
            field=models.CharField(default="🙂", max_length=5),
        ),
        migrations.AlterField(
            model_name="mooddata",
            name="mood_rating",
            field=models.CharField(
                choices=[
                    ("ecstatic", "🤩 Ecstatic"),
                    ("happy", "😁 Happy"),
                    ("neutral", "😐 Neutral"),
                    ("confused", "😕 Confused"),
                    ("worried", "😟 Worried"),
                    ("sad", "😢 Sad"),
                    ("crying", "😭 Crying"),
                    ("disappointed", "😞 Disappointed"),
                    ("angry", "😡 Angry"),
                    ("frustrated", "😤 Frustrated"),
                    ("confident", "😎 Confident"),
                    ("annoyed", "😖 Annoyed"),
                    ("stressed", "😓 Stressed"),
                    ("relieved", "😌 Relieved"),
                    ("thinking", "🤔 Thinking"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="mood_rating",
            field=models.CharField(
                choices=[
                    ("ecstatic", "🤩 Ecstatic"),
                    ("happy", "😁 Happy"),
                    ("neutral", "😐 Neutral"),
                    ("confused", "😕 Confused"),
                    ("worried", "😟 Worried"),
                    ("sad", "😢 Sad"),
                    ("crying", "😭 Crying"),
                    ("disappointed", "😞 Disappointed"),
                    ("angry", "😡 Angry"),
                    ("frustrated", "😤 Frustrated"),
                    ("confident", "😎 Confident"),
                    ("annoyed", "😖 Annoyed"),
                    ("stressed", "😓 Stressed"),
                    ("relieved", "😌 Relieved"),
                    ("thinking", "🤔 Thinking"),
                ],
                max_length=20,
            ),
        ),
    ]
